# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ct < Formula
  desc "Config file format transformer"
  homepage "https://github.com/conways-glider/ct"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conways-glider/ct/releases/download/1.0.7/ct_darwin_x86_64.tar.gz"
      sha256 "588d07808c23fe1cbe9c4bb68ac4dba7aaf976a10ffef88122e238c947f97d43"

      def install
        bin.install "ct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conways-glider/ct/releases/download/1.0.7/ct_darwin_arm64.tar.gz"
      sha256 "86ee4fe782928e4091c35530c7b36ae237441063bd8aca7c5c5ca9956cb6fe3d"

      def install
        bin.install "ct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/conways-glider/ct/releases/download/1.0.7/ct_linux_x86_64.tar.gz"
      sha256 "67ef310aea0864c42a13ae3506d68cf5e30879e1bd4ab89a7c731f20d3db6bce"
      def install
        bin.install "ct"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/conways-glider/ct/releases/download/1.0.7/ct_linux_arm64.tar.gz"
      sha256 "5e9be6aabca6bf900682395529269952007a5d47456ae064a5a321561c28ceb6"
      def install
        bin.install "ct"
      end
    end
  end
end
