# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ct < Formula
  desc "Config file format transformer"
  homepage "https://github.com/conways-glider/ct"
  version "1.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conways-glider/ct/releases/download/1.0.9/ct_darwin_x86_64.tar.gz"
      sha256 "4cce5eba606f606916061dc26e176a6029747fb512e0419b7ec8f69becb1e307"

      def install
        bin.install "ct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conways-glider/ct/releases/download/1.0.9/ct_darwin_arm64.tar.gz"
      sha256 "6b6e902e8498b9977b9448f8d6df933c5c948491c6545d36c8e25d722766f1a6"

      def install
        bin.install "ct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/conways-glider/ct/releases/download/1.0.9/ct_linux_x86_64.tar.gz"
      sha256 "2fb684222bd320ab8b1a08e7074e10fadef697ac4a6e7cbb59ecd8cde6a8a9a8"
      def install
        bin.install "ct"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/conways-glider/ct/releases/download/1.0.9/ct_linux_arm64.tar.gz"
      sha256 "e43cc61a74fa6505b739fae6298a5911d591fbda5abda2e81bc3cad5750a543a"
      def install
        bin.install "ct"
      end
    end
  end
end
