# This file was generated by GoReleaser. DO NOT EDIT.
cask "ct" do
  desc "Config file format transformer"
  homepage "https://github.com/conways-glider/ct"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ct"

  on_macos do
    on_intel do
      url "https://github.com/conways-glider/ct/releases/download/1.0.10/ct_darwin_x86_64.tar.gz"
      sha256 "d176181401be5253cbce3b1eae52a9e485fd308219d621d93fafcfa34b308007"
    end
    on_arm do
      url "https://github.com/conways-glider/ct/releases/download/1.0.10/ct_darwin_arm64.tar.gz"
      sha256 "5f6ba4134dc0e95bc707938256b1bf9e485cb353a04cb2dea760ba41db63d658"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/conways-glider/ct/releases/download/1.0.10/ct_linux_x86_64.tar.gz"
      sha256 "b0207fb0c7dd86201a39b4f1ee5689120e0301848f8c291ddf1fd1472c171062"
    end
    on_arm do
      url "https://github.com/conways-glider/ct/releases/download/1.0.10/ct_linux_arm64.tar.gz"
      sha256 "1c2a89d3a32b33d9ec703026b775518045500143e19f7553d1fbf2c3af0931ed"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ct"]
    end
  end

  # No zap stanza required
end
