# This file was generated by GoReleaser. DO NOT EDIT.
cask "ct" do
  desc "Config file format transformer"
  homepage "https://github.com/conways-glider/ct"
  version "1.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ct"

  on_macos do
    on_intel do
      url "https://github.com/conways-glider/ct/releases/download/1.0.11/ct_darwin_x86_64.tar.gz"
      sha256 "9275f075b8b6730eb4ce1cd81c1db060b3a741f6736591314004739ff19e4d9c"
    end
    on_arm do
      url "https://github.com/conways-glider/ct/releases/download/1.0.11/ct_darwin_arm64.tar.gz"
      sha256 "c6b525e12e01c87302e40a1ded7c9b51b8cf8208adebe36c021da9f8482d6540"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/conways-glider/ct/releases/download/1.0.11/ct_linux_x86_64.tar.gz"
      sha256 "2d0567994a33ca5f8ba9442511f400ab598c9213546021a084c94c71ab4bc1e2"
    end
    on_arm do
      url "https://github.com/conways-glider/ct/releases/download/1.0.11/ct_linux_arm64.tar.gz"
      sha256 "a91654e95ed61977ff475562dfe890ade07aaa977cb3fd8f5d31354903c3fb62"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ct"]
    end
  end

  # No zap stanza required
end
